### ISSUE TITLE
Webserver won't start on android 5.1.1 r2

### ISSUE THREAD

**Issue by Ashraaf** [Free-Software-for-Android/AdAway#630]
Tried with official nightly cm12.1 19/5/2015 which have been upgraded to 5.1.1 r2, webserver not starting at all, tried reinstall, reboot, use inbuild cm superuser, try with supersu. All workaround didn't work. Older cm work flawlessly.

Using Samsung Galaxy S5(SM-G900F) (KLTE), also using latest adaway 3.0.

**Comment by sir-brickalot** [comment]
Doesn't work here either. 12.1-optimized for Samsung Galaxy S4 i9505.

**Comment by 0-kaladin** [comment]
Would need to see a logcat to assist in this issue.

**Comment by sir-brickalot** [comment]
Here is a log file. Android Version: 5.1.1/3.4.108-Alucard kernel/SELinux: Moderate

https://www.dropbox.com/s/3ppg9curl8tsmgq/2015-08-06-17-36-56-adaway.txt.zip?dl=0

**Comment by 0-kaladin** [comment]
thanks i see the webserver starting but nothing of value after that.  can you go to adaway preferences and enable debug?  restart, then logcat again?  maybe debug will show more.

**Comment by sir-brickalot** [comment]
Sorry for my late answer. I enabled debugging in AdAway and created a new log (attached). I tested the button at least three times.
How could I check if the problem is just a display error and the webserver is actually working?

https://www.dropbox.com/s/8jdos2sqqtt9htf/2015-08-18-12-15-26-adaway.txt.zip?dl=0

**Comment by 0-kaladin** [comment]
so it is now running fine for you?
