### ISSUE TITLE
Permissions used by AdAway

### ISSUE THREAD

**Issue by Gitoffthelawn** [Free-Software-for-Android/AdAway#661]
According to the XPrivacy Xposed module, AdAway v3.0.2 uses the `Phone` permission to access `Configuration.MCC` and `Configuration.MNC`. XPrivacy also shows that AdAway uses the `System` permission to access `getRunningAppProcesses`. Finally, according to XPrivacy, it uses the `Identification` permission to access `/proc` and `SERIAL`.  (XPrivacy also shows that AdAway uses a number of other permissions that are clearly essential to its functionality.)

Are all the above permissions really used by AdAway? If so, what purpose do they serve?

**Comment by dschuermann** [comment]
You know that AdAway uses root access? We could strip away every one of the mentioned permissions and do everything via root access. I know this sounds rough, but when allowing root the whole permissions discussion is worthless.
I haven't looked into XPrivacy, but our used permissions are in https://github.com/Free-Software-for-Android/AdAway/blob/master/AdAway/src/main/AndroidManifest.xml which don't match what you say.

**Comment by Gitoffthelawn** [comment]
It's only a matter of understanding the discrepancy... nothing more (or less).

**Comment by dschuermann** [comment]
@Gitoffthelawn Sry that I answered so rough. I don't have any insights into XPrivacy, looks like it would take some time to understand what they are showing.

**Comment by Gitoffthelawn** [comment]
@dschuermann No problem... apology accepted.

I am learning XPrivacy for the first time, so I am not an expert on it (yet).

If you are interested, it shows very precise logs of what an app accesses.  I am surprised by what it reports AdAway is accessing, but I have not learned enough about it (or AdAway) to understand the discrepancies between what it reports and what one would expect.

**Comment by 0-kaladin** [comment]
I'll add my own 2 cents to this.  First, I'd actually ask Xprivacy about any discrepancies in what it reports.  You can see the permissions adaway requires right in the manifest (this is open source application).  It'd be different if this were a closed source application and Xprivacy reported things so you wanted to ask the app developer.  But in this case you can see the source and exactly what adaway is doing and why.
Let's just take your first as an example; "using phone perm to access Configuration.MCC and Configuration.MNC."
Grepping the source for telephony we first see in the manifest:
``<uses-feature android:name="android.hardware.telephony"``
now lets see why:
in ApplyUtils.java you'll see a function ``isApnProxySet``.  And a very nice comment:
`` 
/**
     * Returns true when an APN proxy is set. This means data is routed through this proxy. As a
     * result hostname blocking does not work reliable because images can come from a different
     * hostname!
``

which seems to throw a status code if you have an apn proxy set that would prevent adaway from blocking any ads.

So now you should be enabled to find the discrepancies yourself, I have no interest in matching a report from Xprivacy to the source code here.  Again, if this were a closed source app I could see you asked the developer for more information on the WHY of using a permission.  But since it is right here in the source feel free to go through it.

**Comment by Gitoffthelawn** [comment]
I think it comes down to a time thing... for me to learn another programming language and then read and understand someone else's source code would take weeks or months.  But if it only takes a developer 2 minutes to write "I access data xyz to perform abc", it seems like a reasonable question to pose.
