### ISSUE TITLE
Add more lists

### ISSUE THREAD

**Issue by agilob** [Free-Software-for-Android/AdAway#663]
I checked some other lists from µblock that could be added to AdAway:

* http://www.malwaredomainlist.com/hostslist/hosts.txt
* https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
* https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt
* http://someonewhocares.org/hosts/hosts

Let me know what you think about it.

**Comment by dschuermann** [comment]
Please read https://github.com/Free-Software-for-Android/AdAway/wiki/HostsSources#what-are-the-criteria-to-make-a-hosts-source-default-in-adaway

**Comment by agilob** [comment]
ok, that explains why there are only 4 lists. thanks.

**Comment by 0-kaladin** [comment]
Personally, i strongly recommend you add the malwaredomainlist one yourself.  I've been using it for years with no issues.  Even though dschuermann doesn't want it as a default "Malware blocking hosts sources are not included, because they would add too many entries", it is only 86kb and blocks over 1800 domains that you will never want to visit accidentally.  They are reputable and diligent in adding and removing domains from their list.  Alas this is adaway not malwareaway but definitely take a moment to manually add that to your lists. It won't harm anything and may protect you from a 0 day.
