### ISSUE TITLE
greek translation

### ISSUE THREAD

**Issue by 0-kaladin** [Free-Software-for-Android/AdAway#673]
@dschuermann 
this was posted in the forum, do you know what it is referring to?:

>Hello developers of AdAway. Thank you for the amazing app you created. 
>Today I've received an unexpected email, reading:
>"Hi -,
>Dominik Schürmann rejected the request for Greek (Greece) in the project AdAway of the organization dominikschuermann. "
>I have no idea why I received it. I don't remember requesting such a thing and I could not even contribute to the translation either. For some reason I was not allowed. For starters I'd like to say that I never like it when apps enforce the local language UI. I always prefer the English language and most of the time there is no option to enforce English. 
>I was wondering though, even though up to now Adaway enforced Greek language, even though someone or some team invested their time for the Greek translation that there already is on Transifex, why has it been rejected and why is going to be removed from now on?

**Comment by dschuermann** [comment]
I rejected "Greek (Greece)" but allowed "Greek". It gets too messy if we allow different regions per language. In most cases the main language is enough. This is also written on top of https://www.transifex.com/dominikschuermann/adaway/language/ast/

Not sure why he received such an email if he didn't request it. Should not happen.

**Comment by 0-kaladin** [comment]
thanks for the clarification, i've directed him here from the forum to read response.

**Comment by mandragoras** [comment]
Thank you both. I now understand from your response, Dominik, that I misinterpreted the content of the email. I didn't really understand though what's on top of the link you provided, related to this issue. I can only suppose you meant the Greek translation because I couldn't find anything else. Regarding the notification in the email I received, I probably have accidentally requested it in my effort to contribute to the Greek translation, without realizing I'm doing it the wrong way. Maybe I confused a translation request with a request to join a translation team. I can't remember what I did really.
