### ISSUE TITLE
AdAway speed improvements

### ISSUE THREAD

**Issue by Gitoffthelawn** [Free-Software-for-Android/AdAway#674]
Amazing job increasing speed of AdAway creating the *hosts* file.  Great job!

I now notice that processing the whitelist/blacklist is quite slow.

Can similar improvements be made to those functions?

**Comment by 0-kaladin** [comment]
Short answer: no.
Long answer: 
The speed improvement was gained in the part after all the processing of the different hosts sources are merged, duplicated entries removed, and then it finally goes to write the resultant entries to the hosts file.  There was a specific reason I looked at making that quicker. Introducing IPv6 only impacted that task since when you check the IPv6 option, it would simply do 2 writes instead of 1 for every entry.  No other part of parsing the hosts file is impacted, but when you check to enable IPv6, EVERY entry is written once with 127.0.0.1 and then AGAIN as ::1.  This meant that someone turning on that check box would now double their write time.  So I loaded the largest hosts file source I could, MOABB which had a resultant hosts file (if i recall) of about 45mb.  I timed how long it would take to just write it and it took about 45 sec.  After the improvements to writing it went to under 20 seconds I believe.  Which means writing twice the amount with the IPv6 bumps it back up to 40 secs.  So this meant that enabling IPv6 would give you no longer write time in the new version and everyone would be used to the normal amount of time it took and that was my real goal.  
This performance improvement was gained simply by adding a buffer to the writes.  The processing part is a function that has to loop through every entry line by line.  There is no easy way to speed that up (not saying its impossible) but we are also talking 10 seconds on default hosts sources.  So the reason the short answer is no, is I don't care to find some way to cut the 10 seconds to 8.  My goal was to introduce a feature (ipv6) and have it NOT negatively impact the time spent building the hosts file from what was the norm.  With the default hosts sources this is arguably almost imperceptible anyway, i think the building phase took a few seconds and now it flashes by in a second if you don't have ipv6 checked.  I was only testing with a large hosts file that I would never use for real to measure full seconds and not split seconds.

**Comment by Gitoffthelawn** [comment]
Great explanation... thanks!

It definitely feels faster now... especially on slower devices.  On one device, it was taking over a minute to update... the changes probably shaved at least 20 seconds off that time.

**Comment by Gitoffthelawn** [comment]
I was thinking a little more about this issue.  Merging together 4 very large (thousands of items) *hosts* lists takes much less time than merging in 2 very tiny (less than 10 items) white/blacklists.  Is that indicative of an issue or does that make sense to you?

**Comment by Gitoffthelawn** [comment]
@0-kaladin ping

**Comment by 0-kaladin** [comment]
If the small one seems hung it's an issue but if it goes through the normal cadence of steps that's fine. You didn't specify any times but if it's taking 10 seconds I wouldn't worry about it.

**Comment by Gitoffthelawn** [comment]
@0-kaladin I'll time it and report back.  My thought is that perhaps there is an underlying issue since merging together 4 large hosts lists is so much faster than merging in a couple white/blacklists that contain just a handful of items.

The amount of time it takes could be indicative of a possible issue in how those white/blacklists are being processed.  The actual output seems fine, although I have only performed a cursory check.

**Comment by Gitoffthelawn** [comment]
I performed some more research, and processing manual allow/block items definitely take exponentially longer than items in regular third-party lists.

To test this, I copied all my allow/block items into a list and hosted it.  Then I removed all the manual allow/block items from AdAway.  Now updating lists is *much* faster.

As an implementation workaround, AdAway could just create an internal temporary composite list consisting of the allow/block items, and then merge it like it is a regular list.

If you can, reopen this issue so we can track it.
