### ISSUE TITLE
Add amalgamated hosts file

### ISSUE THREAD

**Issue by SecUpwN** [Free-Software-for-Android/AdAway#723]
I recently discovered the repo [hosts](https://github.com/StevenBlack/hosts) by @StevenBlack, which looks like it is meant to be a unified resource. @dschuermann, please have a look and see if adding it makes `AdAway` more effective.

**Comment by dschuermann** [comment]
I added this already to https://github.com/Free-Software-for-Android/AdAway/wiki/HostsSources . The main problem with this is that I am not sure what Github thinks if we make it default in AdAway. AdAway would then contact Github every morning to check for updates. The installation base of AdAway is roughly 300,000 active installs...

**Comment by SecUpwN** [comment]
>The main problem with this is that I am not sure what Github thinks if we make it default in AdAway.

I've done you the favor and contacted @GitHub support to answer this here. They should reply shortly.

**Comment by 0-kaladin** [comment]
I must be missing the point. That github basically has the hosts file's adaway already includes and has them merged.  its not like it will save adaway processing time since it will still have to do its own merging unless we are saying this will be the only hosts file added now.  It has one source Adaway doesn't include by default.  I'm also opposed to even adding that source.  The real goal of users should be to add as few as possible sources that block the ads that would be shown on their device.  Hence I'd keep default sources low and leverage the blacklist for the few things that may remain.

**Comment by dschuermann** [comment]
Yup, you are right @0-kaladin , my thought was to replace all current lists with this one, but your points are valid. It contains too many non-ad-related hosts.

Also, this is the response I expected from Github, i.e., this can not be made default when hosted on Github.

**Comment by Gitoffthelawn** [comment]
Given the points made by @0-kaladin and the agreement by @dschuermann, the following may be moot, but I'll mention it because, well, I want to (lol):

I don't think GitHub is saying "no".  I think they are saying that only if it becomes a problem, the answer is "no".  Someone would have to look at the scale of GitHub, and see if a few hundred thousand people downloading a small file throughout the day would cause any significant impact.  They wouldn't all be the same time due to different time zones across our little planet.

But it may not even be that many hits, as it would only be the people that have AdAway set to check every day.  I wonder if that option is designed optimally, because even if the lists have been updated, the user must reboot for them to be effective.  It begs the question: How many people are willing to reboot that frequently?
