### ISSUE TITLE
FotMob stops sending push notifications (Urban Airship)

### ISSUE THREAD

**Issue by cnordvik** [Free-Software-for-Android/AdAway#742]
We have 5 emails today from AdAway users saying push alerts are no longer working. Did you add any Urban Airship specific blocking lately? They all had AdAway installed and never heard of the issue until today.

**Comment by 0-kaladin** [comment]
AdAway itself doesn't add any domains to block.  Well we do have one host source but it hasn't been updated in a while.  AdAway includes a few default hosts sources, listed here: https://github.com/Free-Software-for-Android/AdAway/wiki/HostsSources
which could have updated to block urbanairship.  You'd just have to grab their list and see if urbanairship was added recently.  They all typically have forums for add/removing from their lists.  HTH.

**Comment by cnordvik** [comment]
Ok, we got this from our users: 
"In Adaway, there are 4 standard lists. I has all 4 in operation. In the end, I restored to normal, then relocked, just using the top list only, Fotmob worked fine after that. So it was on one of the bottom 3 lists."

"I just used whatever host files AdAway automatically downloads."

"AdAway and default settings"

I guess I will have to try this myself and start digging into why it happens since it seems a lot of users are using AdAway :-/

**Comment by rusegithub** [comment]
Instead of whitelisting *.airship.com in Adaway as Fotmob suggests in the app, whitelist *.urbanairship.com

Fotmob's FAQ has it correct - https://www.fotmob.com/faq - but the app's pop up message when you click TEST NOTIFICATION is wrong, I think. Fotmob's kind and helpful CEO, cnordvik, has been informed so it might be fixed by the time you are reading this.
