### ISSUE TITLE
Adaway false alarm?

### ISSUE THREAD

**Issue by al3xv3gas** [Free-Software-for-Android/AdAway#768]
Ok so I scanned my phone with CM security and Malware Bytes and both said that my device is clean, but Adaway marked an App that I made with an online engine by the name of AppsGeyser as adware. Is my phone infected or whaaat???

**Comment by 0-kaladin** [comment]
The adaway scanner doesn't scan for infections like those other apps.  it scans for apps that may use services that can deliver adds without going through dns.  IE Adaway can not block them.  they would be delivered directly as push and potentially even when the app isn't running.  Makes sense since you made the app, appgeyser probably gets paid by delivering ads

**Comment by al3xv3gas** [comment]
Soi this app is NOT a virus? I need to know because I'm distributing this app to users who are in my community!
